name: プログラミング基礎（C言語）

on:
  push:

permissions:
  checks: write
  actions: read
  contents: read

env:
  DIR: SO201-プログラミング基礎（C言語）/src

jobs:
  setup:
    name: セットアップ
    runs-on: ubuntu-latest
    outputs:
      SO201_01_Q1: ${{ steps.filter.outputs.SO201_01_Q1 }}
      SO201_02_Q1: ${{ steps.filter.outputs.SO201_02_Q1 }}
      SO201_03_Q1: ${{ steps.filter.outputs.SO201_03_Q1 }}
      SO201_03_Q2: ${{ steps.filter.outputs.SO201_03_Q2 }}
      SO201_03_Q3: ${{ steps.filter.outputs.SO201_03_Q3 }}
      SO201_04_Q1: ${{ steps.filter.outputs.SO201_04_Q1 }}
      SO201_04_Q2: ${{ steps.filter.outputs.SO201_04_Q2 }}
      SO201_05_Q1: ${{ steps.filter.outputs.SO201_05_Q1 }}
      SO201_05_Q2: ${{ steps.filter.outputs.SO201_05_Q2 }}
      SO201_05_Q3: ${{ steps.filter.outputs.SO201_05_Q3 }}
      SO201_05_Q4: ${{ steps.filter.outputs.SO201_05_Q4 }}
      SO201_05_Q5: ${{ steps.filter.outputs.SO201_05_Q5 }}
      SO201_05_Q6: ${{ steps.filter.outputs.SO201_05_Q6 }}
      SO201_06_Q1: ${{ steps.filter.outputs.SO201_06_Q1 }}
      SO201_06_Q2: ${{ steps.filter.outputs.SO201_06_Q2 }}
      SO201_06_Q3: ${{ steps.filter.outputs.SO201_06_Q3 }}
      SO201_06_Q4: ${{ steps.filter.outputs.SO201_06_Q4 }}
      SO201_06_Q5: ${{ steps.filter.outputs.SO201_06_Q5 }}
      SO201_07_Q1: ${{ steps.filter.outputs.SO201_07_Q1 }}
      SO201_07_Q2: ${{ steps.filter.outputs.SO201_07_Q2 }}
      SO201_08_Q1: ${{ steps.filter.outputs.SO201_08_Q1 }}
      SO201_08_Q2: ${{ steps.filter.outputs.SO201_08_Q2 }}
      SO201_08_Q3: ${{ steps.filter.outputs.SO201_08_Q3 }}
      SO201_08_Q4: ${{ steps.filter.outputs.SO201_08_Q4 }}
      SO201_09_Q1: ${{ steps.filter.outputs.SO201_09_Q1 }}
      SO201_09_Q2: ${{ steps.filter.outputs.SO201_09_Q2 }}
      SO201_09_Q3: ${{ steps.filter.outputs.SO201_09_Q3 }}
      SO201_09_Q4: ${{ steps.filter.outputs.SO201_09_Q4 }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          SO201_01_Q1: ${{ env.DIR }}/SO201_01_Q1.c
          SO201_02_Q1: ${{ env.DIR }}/SO201_02_Q1.c
          SO201_03_Q1: ${{ env.DIR }}/SO201_03_Q1.c
          SO201_03_Q2: ${{ env.DIR }}/SO201_03_Q2.c
          SO201_03_Q3: ${{ env.DIR }}/SO201_03_Q3.c
          SO201_04_Q1: ${{ env.DIR }}/SO201_04_Q1.c
          SO201_04_Q2: ${{ env.DIR }}/SO201_04_Q2.c
          SO201_05_Q1: ${{ env.DIR }}/SO201_05_Q1.c
          SO201_05_Q2: ${{ env.DIR }}/SO201_05_Q2.c
          SO201_05_Q3: ${{ env.DIR }}/SO201_05_Q3.c
          SO201_05_Q4: ${{ env.DIR }}/SO201_05_Q4.c
          SO201_05_Q5: ${{ env.DIR }}/SO201_05_Q5.c
          SO201_05_Q6: ${{ env.DIR }}/SO201_05_Q6.c
          SO201_06_Q1: ${{ env.DIR }}/SO201_06_Q1.c
          SO201_06_Q2: ${{ env.DIR }}/SO201_06_Q2.c
          SO201_06_Q3: ${{ env.DIR }}/SO201_06_Q3.c
          SO201_06_Q4: ${{ env.DIR }}/SO201_06_Q4.c
          SO201_06_Q5: ${{ env.DIR }}/SO201_06_Q5.c
          SO201_07_Q1: ${{ env.DIR }}/SO201_07_Q1.c
          SO201_07_Q2: ${{ env.DIR }}/SO201_07_Q2.c
          SO201_08_Q1: ${{ env.DIR }}/SO201_08_Q1.c
          SO201_08_Q2: ${{ env.DIR }}/SO201_08_Q2.c
          SO201_08_Q3: ${{ env.DIR }}/SO201_08_Q3.c
          SO201_08_Q4: ${{ env.DIR }}/SO201_08_Q4.c
          SO201_09_Q1: ${{ env.DIR }}/SO201_09_Q1.c
          SO201_09_Q2: ${{ env.DIR }}/SO201_09_Q2.c
          SO201_09_Q3: ${{ env.DIR }}/SO201_09_Q3.c
          SO201_09_Q4: ${{ env.DIR }}/SO201_09_Q4.c
  
  SO201_01_Q1:
    name: 1.はじめに 練習問題1
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_01_Q1 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt install gcc-11
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_01_Q1

  SO201_02_Q1:
    name: 2.基本構文 練習問題1
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_02_Q1 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_02_Q1

  SO201_03_Q1:
    name: 3.変数とデータ型 練習問題1
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_03_Q1 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_03_Q1

  SO201_03_Q2:
    name: 3.変数とデータ型 練習問題2
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_03_Q2 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_03_Q2

  SO201_03_Q3:
    name: 3.変数とデータ型 練習問題3
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_03_Q3 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_03_Q3

  SO201_04_Q1:
    name: 4.演算子 練習問題1
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_04_Q1 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_04_Q1

  SO201_04_Q2:
    name: 4.演算子 練習問題2
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_04_Q2 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_04_Q2

  SO201_05_Q1:
    name: 5.制御構文 練習問題1
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_05_Q1 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_05_Q1

  SO201_05_Q2:
    name: 5.制御構文 練習問題2
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_05_Q2 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_05_Q2

  SO201_05_Q3:
    name: 5.制御構文 練習問題3
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_05_Q3 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_05_Q3

  SO201_05_Q4:
    name: 5.制御構文 練習問題4
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_05_Q4 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_05_Q4

  SO201_05_Q5:
    name: 5.制御構文 練習問題5
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_05_Q5 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_05_Q5

  SO201_05_Q6:
    name: 5.制御構文 練習問題6
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_05_Q6 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_05_Q6

  SO201_06_Q1:
    name: 6.関数 練習問題1
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_06_Q1 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_06_Q1

  SO201_06_Q2:
    name: 6.関数 練習問題2
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_06_Q2 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_06_Q2

  SO201_06_Q3:
    name: 6.関数 練習問題3
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_06_Q3 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_06_Q3

  SO201_06_Q4:
    name: 6.関数 練習問題4
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_06_Q4 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_06_Q4

  SO201_06_Q5:
    name: 6.関数 練習問題5
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_06_Q5 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_06_Q5

  SO201_07_Q1:
    name: 7.クラス 練習問題1
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_07_Q1 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_07_Q1

  SO201_07_Q2:
    name: 7.クラス 練習問題2
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_07_Q2 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_07_Q2

  SO201_08_Q1:
    name: 8.ファイル処理 練習問題1
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_08_Q1 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_08_Q1

  SO201_08_Q2:
    name: 8.ファイル処理 練習問題2
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_08_Q2 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_08_Q2

  SO201_08_Q3:
    name: 8.ファイル処理 練習問題3
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_08_Q3 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_08_Q3

  SO201_08_Q4:
    name: 8.ファイル処理 練習問題4
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_08_Q4 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_08_Q4

  SO201_09_Q1:
    name: 9.プログラミング演習 問題1
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_09_Q1 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_09_Q1

  SO201_09_Q2:
    name: 9.プログラミング演習 問題2
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_09_Q2 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_09_Q2

  SO201_09_Q3:
    name: 9.プログラミング演習 問題3
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_09_Q3 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_09_Q3

  SO201_09_Q4:
    name: 9.プログラミング演習 問題4
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.SO201_09_Q4 == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
      - run: |
          python UnitTest.py --terminate 1 --keyword SO201_09_Q4
